name: tetbee__base
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  ##State Management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  ##Firebase
  # firebase_core: ^3.10.1
  # firebase_auth: ^5.4.1
  # cloud_firestore: ^5.6.2
  # firebase_storage: ^12.4.1
  # firebase_messaging: ^15.2.1
  ##Auth
  google_sign_in: ^6.2.2
  ## Utils
  freezed_annotation: ^2.4.4
  freezed: ^2.5.8
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  go_router: ^14.7.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_form_builder: ^9.7.0
  uuid: ^4.5.1

  font_awesome_flutter: ^10.8.0
  convex_bottom_bar: ^3.2.0
  timeago: ^3.7.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
