name: tetbee__base
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  ##State Management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  ##Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.1
  cloud_functions: ^5.5.1
  ##Auth
  google_sign_in: ^6.2.2
  ## Utils
  top_snackbar_flutter: ^3.3.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_form_builder: ^10.0.1
  uuid: ^4.5.1
  flex_color_picker: ^3.7.1
  intl_phone_field: ^3.2.0
  syncfusion_flutter_datepicker: ^29.2.4
  time_range_picker: ^2.3.0
  font_awesome_flutter: ^10.8.0
  convex_bottom_bar: ^3.2.0
  timeago: ^3.7.0

  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.12
  range_slider_flutter: ^0.0.2
  like_button: ^2.1.0
  flutter_swipe_action_cell: ^3.1.5
  animate_do: ^4.2.0
  url_launcher: ^6.3.1

  lat_lng_to_timezone: ^0.2.0
  timezone: ^0.10.1
  flutter_dotenv: ^5.2.1
  rflutter_alert: ^2.0.7
  freezed_annotation: ^2.4.4
  animated_text_kit: ^4.2.3
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
