enum DataModel {
  appInfo,
  userModel,
  tempUserAvailabilities,
  workPlace,
  placePosition,
  availabilityReceiver,
  scheduleContainer,
  userSchedule,
  joinRequest,
  userAvailabilities,
  workPlaceSchedulePresetTimes,
  chatRoom,
  message,
  notificationCenter,
  appNotification,
  storedData,
}
